name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Start test server
        run: |
          npx http-server . -p 8000 &
          sleep 2 # Wait a moment for the server to start
      - name: Run tests
        run: npm run ci

